### ISSUE TITLE
issue about torch_radon.radon import FanBeam

### ISSUE THREAD

**Issue by boktae7** [DeepXuan/DuDoDp-MAR#2]
Hello. Among the updated codes, mar.py
There is code 'from torch_radon.radon import FanBeam'. 
I installed it from the torch_radon site listed in requirements.txt. However, since torch_raon.radon was missing, I tried to use RadonFanbeam in torch_radon (from torch_radon import RadonFanbeam). In this case, 'CUDA error at cudaMemcpy3D(&myparms) (src/texture.cu:96) error in '_ = fp(Xgt)'. The error 'code: 1, error string: invalid argument' occurs.
Have you ever checked for this error? I'm curious if you know a solution. What should I do if I want to use the code you posted instead of 'RadonFanbeam'?

**Comment by DeepXuan** [comment]
Hi, did you install this version of torchradon?
https://github.com/matteo-ronchetti/torch-radon/tree/c1d3af21a64f4c97e74d37472dccda2294b65ae2
Because there are changes in the API between different versions of torchradon, I am using the version of the tag above.

**Comment by boktae7** [comment]
Thank you for your reply. If you access the site using a method other than the link you sent, version 1.0.0 is displayed. I solved it!

**Comment by Overflowu7** [comment]
> Hi, did you install this version of torchradon? https://github.com/matteo-ronchetti/torch-radon/tree/c1d3af21a64f4c97e74d37472dccda2294b65ae2 Because there are changes in the API between different versions of torchradon, I am using the version of the tag above.

I try to install torch_radon in github but it still appear some errors:
  Downloading https://github.com/matteo-ronchetti/torch-radon/tree/c1d3af21a64f4c97e74d37472dccda2294b65ae2
     - 332.2 kB 398.9 kB/s 0:00:01
  ERROR: Cannot unpack file /tmp/pip-unpack-hvw7zvu_/c1d3af21a64f4c97e74d37472dccda2294b65ae2 (downloaded from /tmp/pip-req-build-stdrj1qb, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of /tmp/pip-req-build-stdrj1qb

**Comment by ckr1314** [comment]
> 你好。在更新的代码中，mar.py 有代码“from torch_radon.radon import FanBeam”。我从 requirements.txt 中列出的 torch_radon 站点安装了它。但是，由于缺少 torch_raon.radon，我尝试在 torch_radon中使用 RadonFanbeam（从 torch_radon import RadonFanbeam）。在这种情况下，'_ = fp（Xgt）' 中的 cudaMemcpy3D（&myparms） （src/texture.cu：96） 错误中的 CUDA 错误。出现错误 'code： 1， error string： invalid argument'。您是否检查过此错误？我很好奇你是否知道解决方案。如果我想使用您发布的代码而不是 'RadonFanbeam'，我该怎么办？

你好，测试的时候一直报CUDA error at cudaCreateTextureObject（&texture， &resDesc， &texDesc， NULL） （src/texture.cu：143） error code： 1， error string： invalid argument说创建纹理对象失败，这是什么原因啊

**Comment by YeHooooo** [comment]
> > 你好。在更新的代码中，mar.py 有代码“from torch_radon.radon import FanBeam”。我从 requirements.txt 中列出的 torch_radon 站点安装了它。但是，由于缺少 torch_raon.radon，我尝试在 torch_radon中使用 RadonFanbeam（从 torch_radon import RadonFanbeam）。在这种情况下，'_ = fp（Xgt）' 中的 cudaMemcpy3D（&myparms） （src/texture.cu：96） 错误中的 CUDA 错误。出现错误 'code： 1， error string： invalid argument'。您是否检查过此错误？我很好奇你是否知道解决方案。如果我想使用您发布的代码而不是 'RadonFanbeam'，我该怎么办？
> 
> 你好，测试的时候一直报CUDA error at cudaCreateTextureObject（&texture， &resDesc， &texDesc， NULL） （src/texture.cu：143） error code： 1， error string： invalid argument说创建纹理对象失败，这是什么原因啊

你好，请问这个问题你解决了吗？如果解决了可以麻烦告知一下如何解决吗？
